/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package selenium;

import org.junit.Test;
import static org.junit.Assert.*;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.WebDriverWait;
import static org.openqa.selenium.support.ui.ExpectedConditions.presenceOfElementLocated;
import java.io.File;
import java.net.http.WebSocket;
import java.time.Duration;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testSelenium(){
        App.setUpChromeDriver();
        WebDriver driver = new ChromeDriver();
        WebDriverWait wait = new WebDriverWait(driver, 1000);
        try {
            driver.get("http://localhost:3000/");
            WebElement button = wait.until(presenceOfElementLocated(By.cssSelector("a")));
            button.click();
            WebElement name = wait.until(presenceOfElementLocated(By.cssSelector("#name")));
            name.sendKeys("Test");
            WebElement desc = wait.until(presenceOfElementLocated(By.cssSelector("#description")));
            desc.sendKeys("hello world");
            WebElement send = wait.until(presenceOfElementLocated(By.cssSelector("button")));
            send.click();
            WebElement item = wait.until(presenceOfElementLocated(By.cssSelector("li > h5")));

            assertEquals("Name are equal", "Test", item.getText());
        } finally {
            driver.quit();
        }
        
    }
}
